services:
  # ------------------- Enquiry Databases -------------------
  postgres-enquiry:
    image: postgres:17
    container_name: postgres-enquiry
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: real_state_enquiries
    volumes:
      - pg_enquiry_data:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
    networks:
      - realState_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # ------------------- Auth pg Databases -------------------
  postgres-auth:
    image: postgres:17
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: real_state_pg
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
#    ports:
#      - "5434:5432"
    networks:
      - realState_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # ------------------- Property Mysql Databases -------------------
  mysql-property:
    image: mysql:8.0
    container_name: mysql-property
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: realState_property_mysql
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    volumes:
        - mysql_property_data:/var/lib/mysql
    networks:
        - realState_net
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
        interval: 5s
        timeout: 5s
        retries: 5

  # ------------------- Redis -------------------
  redis-auth:
    image: redis:7
    container_name: redis-auth
#    ports:
#      - "6380:6379"
    networks:
      - realState_net
    volumes:
      - redis_auth_data:/data
    command: [ "redis-server", "--requirepass", "redis", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "redis", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # ---------------- Enquiry Nest Services ----------------
  enquiry-service:
#    build: ./enquiry-service
    image: mykks32/realstate-enquiry-service:latest
    container_name: enquiry-service
    env_file:
      - ./env/enquiry-service.env
    volumes:
      - enquiry_service_data:/usr/src/app/data
    depends_on:
      postgres-enquiry:
        condition: service_healthy
    networks:
      - realState_net
    ports:
      - "3001:3001"
    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s


  # ---------------- Auth Nest Services ----------------
  auth-service:
#    build: ./auth-service
    image: mykks32/realstate-auth-service:latest
    container_name: auth-service
    env_file:
      - ./env/auth-service.env
    volumes:
      - auth_service_data:/usr/src/app/data
    depends_on:
      postgres-auth:
        condition: service_healthy
      redis-auth:
        condition: service_healthy
    networks:
      - realState_net
    ports:
      - "3002:3000"
    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  # ---------------- SpringBoot Property Services ----------------
  property-service:
#    build: ./property-service
    image: mykks32/realstate-property-service:latest
    container_name: property-service
    env_file:
      - ./env/property-service.env
    volumes:
      - property_service_data:/app
    depends_on:
      mysql-property:
        condition: service_healthy
    networks:
      - realState_net
    ports:
      - "8080:8080"
    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  # ---------------- Api Nest Services ----------------
  api-gateway:
#    build: ./api-gateway
    image: mykks32/realstate-api-gateway:latest
    container_name: api-gateway
    env_file:
      - ./env/api-gateway.env
    volumes:
      - api_gateway_data:/usr/src/app/data
    depends_on:
      - auth-service
      - enquiry-service
      - property-service
    networks:
      - realState_net
    ports:
      - "4000:4000"  # Only expose API Gateway to host

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 120s


# ---------------- Volumes ----------------
volumes:
  pg_enquiry_data:
  pg_auth_data:
  enquiry_service_data:
  auth_service_data:
  redis_auth_data:
  api_gateway_data:
  mysql_property_data:
  property_service_data:


# ---------------- Networks ----------------
networks:
  realState_net:
    driver: bridge