name: Deploy Enquiry Service

on:
  push:
    tags:
      - 'v*-enquiry'
    branches:
      - production

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Set Docker image version from tag
      - name: Set Docker image version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}  # e.g., v1.2.3-enquiry
          VERSION=${VERSION#v}              # strip leading 'v' → 1.2.3
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log version
        run: echo "Docker image version is $VERSION"

      # 3. Docker login
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 4. Create env file for enquiry-service
      - name: Create env file
        run: |
          mkdir -p env
          echo "PORT=3001" >> env/enquiry-service.env
          echo "DATABASE_HOST=postgres-enquiry" >> env/enquiry-service.env
          echo "DATABASE_PORT=5432" >> env/enquiry-service.env
          echo "DATABASE_USER=${{ secrets.ENQ_DB_USER }}" >> env/enquiry-service.env
          echo "DATABASE_PASS=${{ secrets.ENQ_DB_PASS }}" >> env/enquiry-service.env
          echo "DATABASE_NAME=real_state_enquiries" >> env/enquiry-service.env

      # 5. Build Docker image
      - run: docker build -t mykks32/real-state/enquiry-service:$VERSION ./enquiry-service

      # 6. Push Docker image
      - run: docker push mykks32/real-state/enquiry-service:$VERSION

      # 7. Tag as latest and push
      - run: |
          docker tag mykks32/real-state/enquiry-service:$VERSION mykks32/enquiry-service:latest
          docker push mykks32/real-state/enquiry-service:latest
